// codebase-memory-mcp:start
// Generated by codebase-memory-mcp for OpenCode.
// Regenerated on install/update from the MCP tool registry, so it cannot
// drift from the tools the server actually serves. Edits inside this block
// are overwritten; edit outside it, or remove the markers to take ownership.
// OpenCode already reaches every tool over MCP; this adds only the
// automatic graph lookup before a grep/glob, which other clients get
// through their own hook configuration.
import { Plugin } from '@opencode/plugin';
import { spawn } from 'node:child_process';

const BIN = '/home/gilles/.local/bin/codebase-memory-mcp';

function augment(tool, args) {
  return new Promise((resolve) => {
    const child = spawn(BIN, ['hook-augment'], {
      stdio: ['pipe', 'pipe', 'ignore'],
      env: { ...process.env, CBM_LOG_LEVEL: 'error' },
    });
    let out = '';
    child.stdout.on('data', (d) => (out += d.toString()));
    child.on('error', () => resolve(''));
    child.on('close', () => resolve(out));
    child.stdin.end(JSON.stringify({
      hook_event_name: 'PreToolUse',
      tool_name: tool,
      tool_input: args ?? {},
    }));
  });
}

export default Plugin.define({
  id: 'cbm-augment',
  async setup(ctx) {
    await ctx.tool.hook('execute.after', async (event) => {
      if (event.status !== 'completed') return;
      const tool = event.tool === 'grep' ? 'Grep' : event.tool === 'glob' ? 'Glob' : null;
      if (!tool) return;
      const extra = await augment(tool, (event.input as Record<string, unknown>) ?? {});
      if (!extra) return;
      const prev = event.result;
      const content = typeof prev.content === 'string'
        ? prev.content + '\n' + extra
        : Array.isArray(prev.content)
          ? [...prev.content, { type: 'text' as const, text: extra }]
          : extra;
      event.result = { ...prev, content };
    });
  },
});
// codebase-memory-mcp:end

// v2-port reload marker
