[Automation]
auto_exit=true
auto_unmount=true
verify_file=false

[Device]
device_autodetection=true
this_computer_path=
this_computer_source=false

[DidYouKnowWindow]
windowSize=@Size(570 376)

[Display]
did_you_know_index=1
did_you_know_on_startup=false
ignore_unhandled_file_exts=TMP, DAT

[ErrorLog]
visible=false
windowPosition=@Point(1920 0)
windowSize=@Size(960 1080)

[MainWindow]
centerSplitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x3\0\0\x1\xf3\0\0\x6\x4\0\0\x2\x3\x1\xff\xff\xff\xff\x1\0\0\0\x1\0)
leftPanelSplitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x3\0\0\x1\x15\0\0\0*\0\0\0\xbf\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
proximityButtonPressed=false
rightButtonPressed=1
rightPanelSplitterSizes=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x5\xb7\0\0\x2P\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
sourceButtonPressed=true
windowPosition=@Point(343 944)
windowSize=@Size(2997 1767)

[Performance]
generate_thumbnails=true
keep_thumbnails_days=30
save_fdo_thumbnails=true
use_thumbnail_cache=true

[Presets]
preset_photo_rename\1\name=perso_1
preset_photo_rename\1\pref_list=Filename, Name, Original Case, Text, _, , Sequences, Stored number, Five digits
preset_photo_rename\size=1
preset_photo_subfolder\1\name=01_septembre_2018
preset_photo_subfolder\1\pref_list=Date time, Download time, DD, Text, _, , Date time, Download time, Month (full), Text, _, , Date time, Download time, YYYY
preset_photo_subfolder\size=1

[Program]
program_version=0.9.11

[Rename]
downloads_today=2018-09-02, 0
photo_download_folder=/home/gilles/PHOTOS
photo_rename=Filename, Name, Original Case, Text, _, , Sequences, Stored number, Five digits
photo_subfolder=Date time, Download time, DD, Text, _, , Date time, Download time, Month (full), Text, _, , Date time, Download time, YYYY
stored_sequence_no=0
synchronize_raw_jpg=true
