[theme_colors]
normal_row_bg = "#020617"
alt_row_bg = "#0F172A"
selected_style = "#1E293B"
status_bar = "#022C22"
tasks_box_bg = "#020617"
tasks_box_outline = "White"
tasks_box_scrollbar = "White"
tasks_info_box_bg = "#020617"
tasks_info_box_outline = "White"
tasks_info_box_scrollbar = "White"
state_box_bg = "#020617"
state_box_outline = "White"
state_box_scrollbar = "White"
help_menu_bg = "#020617"
help_menu_outline = "White"
help_menu_scrollbar = "White"
pop_up_bg = "#1E293B"
pop_up_outline = "White"
state_box_outline_during_tags_edit = "Blue"
highlight_color_bg = "Cyan"
highlight_color_fg = "Black"

[text_colors]
status_open = "Cyan"
status_working = "Blue"
status_paused = "Yellow"
status_completed = "Green"
urgency_low = "Green"
urgency_medium = "Yellow"
urgency_high = "Magenta"
urgency_critical = "Red"
urgency_ascending = "Red"
urgency_descending = "Blue"
title = "Magenta"
created_date = "Cyan"
completed_date = "Green"
latest = "Blue"
description = "Magenta"
tags = "Blue"
layout_smart = "Yellow"
layout_horizontal = "Cyan"
layout_vertical = "Blue"
filter_status_all = "Cyan"
filter_status_completed = "Green"
filter_status_notcompleted = "Yellow"
help_actions = "Blue"
help_quick_actions = "Magenta"
help_movement = "Yellow"

[theme_styles]
scrollbar_begin = "↑"
scrollbar_end = "↓"
scrollbar_thumb = "█"
scrollbar_track = ""
highlight_symbol = ">"
urgency_low = "   "
urgency_medium = "!  "
urgency_high = "!! "
urgency_critical = "!!!"
completed = "✓  "
