
[features]
CodeSpaces = false
Clipboard = true
Logging = false
Timeout = 0.1
Savebrace = false
Images = true
Links = true

[style]
Margin = 2
ListIndent = 2
PrettyPad = true
PrettyBroken = true
Width = 0
HSV = [0.8, 0.5, 0.5]
Dark = { H = 1.00, S = 1.50, V = 0.25 }
Mid = { H = 1.00, S = 1.00, V = 0.50 }
Symbol = { H = 1.00, S = 1.00, V = 1.50 }
Head = { H = 1.00, S = 1.00, V = 1.75 }
Grey = { H = 1.00, S = 0.25, V = 1.37 }
Bright = { H = 1.00, S = 0.60, V = 2.00 }
Syntax = "native"
