; frany.conf
; Qman theme
; description: franky: a dark theme for Qman
; tags:        rgb, unicode, dark
; TERM:        xterm-kitty
; based on:    https://github.com/gravures/franky/blob/main/src/franky/themes/qman.py
; author:      gilles coissac

[chars]
sbar_top=           ┳
sbar_vline=         ┃
sbar_bottom=        ┻
sbar_block=         █
trans_mode_name=    ┇
trans_name_loc=     ┇
box_hline=          ─
box_vline=          │
box_tl=             ╭
box_tr=             ╮
box_bl=             ╰
box_br=             ╯
arrow_up=           ⇡
arrow_down=         ⇣
arrow_lr=           ⇄

[colours]
;                   fg        bg        bold
text=               #b1b1b1   #110E17   false
search=             #ffdeaa   #151524   false
mark=               #ffdeaa   #2a2a3c   false
link_man=           #977ebc   #110E17   false
link_man_f=         #fc8dc7   #110E17   true
link_http=          #749fd4   #110E17   false
link_http_f=        #539bf5   #110E17   true
link_email=         #749fd4   #110E17   false
link_email_f=       #539bf5   #110E17   true
link_file=          #749fd4   #110E17   false
link_file_f=        #539bf5   #110E17   true
link_ls=            #ba8d45   #110E17   false
link_ls_f=          #daaa3f   #110E17   true
sb_line=            #09070D   #09070D   false
sb_block=           #977ebc   #09070D   false
stat_indic_mode=    #09070D   #cba6f7   true
stat_indic_name=    #909dab   #110E17   false
stat_indic_loc=     #909dab   #110E17   false
stat_input_prompt=  #c9c9c9   #110E17   false
stat_input_help=    #57ab5a   #110E17   false
stat_input_em=      #bb3831   #110E17   false
imm_border=         #521f9c   #0B090F   false
imm_title=          #cba6f7   #0B090F   false
sp_input=           #c9c9c9   #0B090F   false
sp_text=            #b1b1b1   #0B090F   false
sp_text_f=          #ba8d45   #0B090F   false
help_text=          #b1b1b1   #0B090F   false
help_text_f=        #ba8d45   #0B090F   false
history_text=       #b1b1b1   #0B090F   false
history_text_f=     #ba8d45   #0B090F   false
toc_text=           #b1b1b1   #0B090F   false
toc_text_f=         #ba8d45   #0B090F   false
