[TextView]
bullet_icon_size=GTK_ICON_SIZE_MENU
indent=30
tabs=None
linespacing=3
wrapped-lines-linespacing=0
font=
justify=
;font=Linux Libertine Display O 12

[Tag strong]
weight=PANGO_WEIGHT_BOLD

[Tag emphasis]
style=PANGO_STYLE_ITALIC

[Tag mark]
background=yellow

[Tag strike]
strikethrough=True
;foreground=#444

[Tag code]
indent=20
family=monospace
background=#ccc
;foreground=#2e3436

[Tag pre]
indent=20
family=monospace
wrap-mode=GTK_WRAP_NONE
;foreground=#2e3436
;background=#ccc

[Tag link]
foreground=yellow

[Tag tag]
foreground=#ce5c00

[Tag h1]
scale=1.3
weight=PANGO_WEIGHT_BOLD
;foreground=#444

[Tag h2]
scale=1.25
weight=PANGO_WEIGHT_BOLD
;foreground=#444

[Tag h3]
scale=1.2
weight=PANGO_WEIGHT_BOLD
;foreground=#444

[Tag h4]
scale=1.15
weight=PANGO_WEIGHT_ULTRABOLD
;foreground=#444

[Tag h5]
style=PANGO_STYLE_ITALIC
scale=1.1
weight=PANGO_WEIGHT_BOLD
;foreground=#444

[Tag h6]
scale=1.05
weight=PANGO_WEIGHT_BOLD
;foreground=#444
