## Hooks
[pre-start]
tmux = """
WORKTREE_PATH={{ worktree_path }}
connect-rendez-vous "$WORKTREE_PATH"
"""

[pre-remove]
tmux = """
SESSION={{ worktree_name }}
close-rendez-vous --kill --yes "$SESSION"
"""
