
# The basic colors
background #110E17
foreground #c9c9c9
selection_background #09070D
selection_foreground #ba8d45

# The 16 terminal colors
color0 #373e47
color1 #bb3831
color2 #57ab5a
color3 #ba8d45
color4 #2764b1
color5 #fc8dc7
color6 #94e2d5
color7 #a6a596
color8 #54595f
color9 #fc8dc7
color10 #94e2d5
color11 #ffdeaa
color12 #539bf5
color13 #f2cdcd
color14 #74c7ec
color15 #b1b1b1

# Cursor colors
cursor #909dab
cursor_text_color #151524

# Scrollbar colors
scrollbar_handle_color  #977ebc
scrollbar_track_color   #09070D

# URL color when hovering with mouse
url_color               #539bf5

# Kitty window border colors
active_border_color     #b1b1b1
inactive_border_color   #54595f
bell_border_color       #ffdeaa

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0B090F
active_tab_background   #cba6f7
inactive_tab_foreground #a6a596
inactive_tab_background #110E17
tab_bar_background      #0B090F

# Colors for marks (marked text in the terminal)
mark1_foreground #110E17
mark1_background #b1b1b1
mark2_foreground #110E17
mark2_background #f2cdcd
mark3_foreground #110E17
mark3_background #74c7ec
