#!/usr/bin/env bash
#
# Search for pattern in files.
#
# search in current drectory: File Previewer

RG_OPTS=(--column --line-number --no-heading --color=always --word-regexp)
PATTERN=(TODO FIXME BUG: HACK: XXX: NOTE:)
# PATTERN="TODO:"

function main() {
  local where patterns

  where=${1:-$(pwd)}
  for item in "${PATTERN[@]}"; do
    patterns="${patterns} -e ${item}"
  done

  (
    cd $where
    rg "${RG_OPTS[@]}" "${patterns}" 2>/dev/null |
      fzf \
        --ansi \
        --exact \
        --prompt='/> ' \
        --header="[ctrl-space]:preview|[tab]:layout|[enter]:$EDITOR|[esc]:quit" \
        --header-first \
        --bind "start:reload:rg ${RG_OPTS[*]} ${PATTERN}" \
        --bind "change:reload:sleep 0.1; rg ${RG_OPTS[*]} ${PATTERN} || true" \
        --bind "ctrl-space:toggle-preview" \
        --bind "tab:change-preview-window(right|up)" \
        --bind "enter:become($EDITOR {1})" \
        --delimiter : \
        --preview-window right,66% \
        --preview 'batcat --color=always {1} --highlight-line {2} --line-range {2}: --theme "Visual Studio Dark+"'
  )
}

main "$@"
