include themes/franky.conf

[mouse]
; Mouse support in some terminal emulators is incomplete and/or buggy. Set this
; to false if you are having mouse trouble.
enable=             true

[misc]
; If using a graphical web browser, uncomment this to suppress an annoying
; flicker after opening an HTTP link
; reset_after_http=   false

; If using a graphical email client, uncomment this to suppress an annoying
; flicker after opening an email link
; reset_after_email=  false

[keys]
; Scroll up one line
up= KEY_UP k KEY_LEFT
; Scroll down one line
down= KEY_DOWN j KEY_RIGHT
; Scroll left one tab stop
left= (
; Scroll right one tab stop
right= )
; Scroll up one page
pgup= KEY_PPAGE K
; Scroll down one page
pgdn= KEY_NPAGE J
; Go to page top
home= KEY_HOME g
; Go to page end
end= KEY_END G
; Open focused link
open= KEY_ENTER LF SPACE
; Perform apropos on the focused link
open_apropos= a
; Perform whatis on the focused link
open_whatis= w
; Open a manual page using a dialog
sp_open= o
; Perform apropos using a dialog
sp_apropos= A
; Perform whatis using a dialog
sp_whatis= W
; Go to index (home) page
index= i
; Go back one step in history
back= KEY_BACKSPACE BS [
; Go forward one step in history
fwrd= ]
; Show history menu
history= h
; Show table of contents
toc= t '
; Forward search
search= /
; Backward search
search_back= ?
; Go to next search result
search_next= n .
; Go to previous search results
search_prev= N ,
; Show this help message
help= #
; Exit the progra
quit= q
